const envPaths = require('./envPaths.json');
require('dotenv').config({ path: envPaths[process.env.NODE_ENV || 'development'] });

const knexBaseConfig = {
    client: process.env.DB || 'sqlite3',
    useNullAsDefault: true,
    migrations: { directory: './server/migrations' }
};

module.exports = {
    test: {
        ...knexBaseConfig,
        connection: {
            filename: process.env.DB_PATH
        },
        seeds: {
            directory: './server/seeds'
        }
    },
    development: {
        ...knexBaseConfig,
        connection: process.env.DB === 'pg' ?
            // Local PostgreSQL connection configs - update PG_USER, PG_PASS, PG_DB in development .env generated by `postinstall` script
            `postgres://${process.env.PG_USER}:${process.env.PG_PASS}@${process.env.PG_HOST}/${process.env.PG_DB}` :
            // sqlite3 connection configs
            {
                filename: process.env.DB_PATH
            },            
        seeds: {
            directory: './server/seeds'
        }
    },
    production: {
        ...knexBaseConfig,
        // DATABASE_URL available in process.env as config var passed by Heroku after setting up a pg instance
        connection: {
            connectionString: process.env.DATABASE_URL,
            ssl: {
                // SSL is not supported in free tier of Heroku's Postgres
                rejectUnauthorized: false
            }
        }
    }
};
